<div style="text-align: center;">
 <img width=600px heigth=40px src="./IMG/Layer_Norm.png" alt="Example image">
 </div>

In [1]:
import torch
import torch.nn as nn
import pandas as pd

In [7]:
torch.manual_seed(123)

In [16]:
batch_example = torch.randn(2,5)
layer = nn.Sequential(nn.Linear(5,6), nn.ReLU())
out = layer(batch_example)

print(out)

tensor([[0.4635, 0.0000, 0.0000, 0.1970, 0.5780, 0.0000],
        [0.0000, 0.0000, 0.3331, 0.2203, 0.0000, 0.3346]],
       grad_fn=<ReluBackward0>)


In [22]:
mean = out.mean(dim=-1, keepdim=True) #dim=-1 last dim which is col her and keepdim to keep the dim
var = out.var(dim=-1, keepdim=True)

In [23]:
print(mean)
print(var)

tensor([[0.2064],
        [0.1480]], grad_fn=<MeanBackward1>)
tensor([[0.0664],
        [0.0280]], grad_fn=<VarBackward0>)


In [20]:
out_Norm=(out-mean)/torch.sqrt(var)

In [ ]:
print(out_Norm.mean(dim=-1,keepdim=True)) #mean is apporate to zero
print(out_Norm.var(dim=-1,keepdim=True))  #var is one

tensor([[-3.7253e-08],
        [-3.9736e-08]], grad_fn=<MeanBackward1>)
tensor([[1.0000],
        [1.0000]], grad_fn=<VarBackward0>)


In [ ]:
class LayerNorm(nn.Module):
  def __init__(self, emb_dim):
    super().__init__()
    self.epsilon=1e-5
    self.shift=nn.Parameter(torch.zeros(emb_dim))
    self.scale=nn.Parameter(torch.ones(emb_dim))
  def forward(self,inp):
    mean = inp.mean(dim=-1, keepdim=True) 
    var = inp.var(dim=-1, keepdim=True)
    input_Norm=(inp-mean)/torch.sqrt(var+self.epsilon)
    return input_Norm*self.scale+self.shift

In [41]:
LN=LayerNorm(out.shape[1])
out_norm=LN.forward(out)
print(out_norm.mean(dim=-1,keepdim=True))
print(out_norm.var(dim=-1,keepdim=True))

tensor([[-7.3885e-08],
        [-2.9802e-08]], grad_fn=<MeanBackward1>)
tensor([[0.9998],
        [0.9996]], grad_fn=<VarBackward0>)
