In [5]:
import torch

In [22]:
#import torch
import torch.nn as nn
# Define a linear layer with input size 3 and output size 2
linear = nn.Linear(3, 2)
# Example input
x = torch.tensor([[1.0, 2.0, 3.0]])
output = linear(x)
print("Output:", output)

Output: tensor([[ 2.8000, -0.2299]], grad_fn=<AddmmBackward0>)


In [23]:
relu = nn.ReLU()

# Example input
x = torch.tensor([[-1.0, 2.0], [3.0, -4.0]])
output = relu(x)
print("Output:", output)

Output: tensor([[0., 2.],
        [3., 0.]])


In [24]:
max_pool = nn.MaxPool2d(kernel_size=2, stride=2)
# Example input (batch of 1, 1 channel, 4x4 image)
x = torch.tensor([[[[1.0, 2.0, 3.0, 4.0],
                    [5.0, 6.0, 7.0, 8.0],
                    [9.0, 10.0, 11.0, 12.0],
                    [13.0, 14.0, 15.0, 16.0]]]])
output = max_pool(x)
print("Output shape:", output.shape)  # Shape: (1, 1, 2, 2)
print("Output:", output)

Output shape: torch.Size([1, 1, 2, 2])
Output: tensor([[[[ 6.,  8.],
          [14., 16.]]]])


In [27]:
flatten = nn.Flatten()
# Example input (batch of 1, 3 channels, 32x32 image)
x = torch.randn(1, 3, 32, 32)
output = flatten(x)
print("Output shape:", output.shape)  # Shape: (1, 3072)

Output shape: torch.Size([1, 3072])


In [36]:
dropout = nn.Dropout(p=0.5)
# Example input
x = torch.tensor([[1.0, 2.0, 3.0, 4.0]])
output = dropout(x)
print("Output during training:", output)

Output during training: tensor([[0., 4., 0., 8.]])


In [39]:
embedding = nn.Embedding(num_embeddings=10, embedding_dim=3)

# Example input (batch of 2, sequence length 4)
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
output = embedding(x)
print("Output shape:", output.shape)  # Shape: (2, 3, 3)
output

Output shape: torch.Size([2, 3, 3])


tensor([[[ 2.4320,  0.1863,  0.3958],
         [-1.4415,  0.3530,  1.2456],
         [-0.2992,  1.1610,  1.0172]],

        [[-1.1089,  0.2319,  0.2284],
         [-1.0114, -0.7274, -1.2209],
         [ 1.4159,  0.2619, -0.6822]]], grad_fn=<EmbeddingBackward0>)

In [ ]:
import torch.nn as nn

# Define the model using nn.Sequential
model = nn.Sequential(
    nn.Linear(10, 20),  # Input layer: 10 features to 20 neurons
    nn.ReLU(),          # Activation function
    nn.Linear(20, 10),  # Hidden layer: 20 neurons to 10 neurons
    nn.ReLU(),          # Activation function
    nn.Linear(10, 1),   # Output layer: 10 neurons to 1 output
    nn.Sigmoid()        # Sigmoid activation for binary classification
)

print(model)

Sequential(
  (0): Linear(in_features=10, out_features=21, bias=True)
  (1): ReLU()
  (2): Linear(in_features=20, out_features=10, bias=True)
  (3): ReLU()
  (4): Linear(in_features=10, out_features=1, bias=True)
  (5): Sigmoid()
)


In [42]:
!pip install PyMuPDF

In [47]:
import fitz
def is_password_protected_pdf(pdf_file_path):
    doc = fitz.Document(pdf_file_path)
    if doc.needs_pass:
        return True
    return False
def is_pdf_text_encrypted(pdf_file_path):
    doc = fitz.Document(pdf_file_path)
    if doc.metadata["encryption"] is not None:
        return True
    return False  

In [49]:
def decrypt_pdf(pdf_file_path, password):
    doc = fitz.Document(pdf_file_path)
    if doc.authenticate(password):
        file_name = "pdf_decrypted.pdf"
        doc.save(file_name)
        print("\Successfully decrypted PDF")
    else:
        print("\t Password incorrect!! Cannot decrypt PDF!!!")

## Onehot Encoding

In [6]:
def to_onehot(y, num_classes):
    y_onehot = torch.zeros(y.size(0), num_classes)
    y_onehot.scatter_(1, y.view(-1, 1).long(), 1).float()
    return y_onehot

y = torch.tensor([0, 1, 2, 2])

y_enc = to_onehot(y, 3)

print('one-hot encoding:\n', y_enc)

one-hot encoding:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.]])


## Softmax

In [7]:
Z = torch.tensor( [[-0.3,  -0.5, -0.5],
                   [-0.4,  -0.1, -0.5],
                   [-0.3,  -0.94, -0.5],
                   [-0.99, -0.88, -0.5]])

Z.shape

torch.Size([4, 3])

Next, we convert them to "probabilities" via softmax:

$$P(y=j \mid z^{(i)}) = \sigma_{\text{softmax}}(z^{(i)}) = \frac{e^{z^{(i)}}}{\sum_{j=0}^{k} e^{z_{k}^{(i)}}}.$$

In [8]:
def softmax(z):
  z_max=torch.max(z,dim=1,keepdim=True).values
  exp_z=torch.exp(z-z_max)
  return exp_z/torch.sum(exp_z,dim=1,keepdim=True)
  
softmax(Z)  

tensor([[0.3792, 0.3104, 0.3104],
        [0.3072, 0.4147, 0.2780],
        [0.4263, 0.2248, 0.3490],
        [0.2668, 0.2978, 0.4354]])

$$\mathcal{L}(\mathbf{W}; \mathbf{b}) = \frac{1}{n} \sum_{i=1}^{n} H(T_i, O_i),$$

$$H(T_i, O_i) = -\sum_m T_i \cdot log(O_i).$$

In [13]:
def softmax(z):
    return (torch.exp(z.t()) / torch.sum(torch.exp(z), dim=1)).t()

smax = softmax(Z)
print('softmax:\n', smax)

softmax:
 tensor([[0.3792, 0.3104, 0.3104],
        [0.3072, 0.4147, 0.2780],
        [0.4263, 0.2248, 0.3490],
        [0.2668, 0.2978, 0.4354]])


In [14]:
def to_classlabel(z):
    return torch.argmax(z, dim=1)

print('predicted class labels: ', to_classlabel(smax))
print('true class labels: ', to_classlabel(y_enc))

predicted class labels:  tensor([0, 1, 0, 2])
true class labels:  tensor([0, 1, 2, 2])


In [16]:
def cross_entropy(softmax, y_target):
    return - torch.sum(torch.log(softmax) * (y_target), dim=1)

xent = cross_entropy(smax, y_enc)
print('Cross Entropy:', xent)

Cross Entropy: tensor([0.9698, 0.8801, 1.0527, 0.8314])


## In pytorch

In [17]:
import torch.nn.functional as F

In [18]:
F.nll_loss(torch.log(smax), y, reduction='none')

tensor([0.9698, 0.8801, 1.0527, 0.8314])

In [19]:
F.cross_entropy(Z, y, reduction='none')

tensor([0.9698, 0.8801, 1.0527, 0.8314])

In [20]:
F.cross_entropy(Z, y)

tensor(0.9335)

In [21]:
torch.mean(cross_entropy(smax, y_enc))

tensor(0.9335)

: 

: 

: 

: 

: 